name: Docker Continuous Integration
on:
  push:
    branches: ["master"]

jobs:
  build_and_deploy:
    name: Build and Deploy Docker
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          
      - name: Get Short Hash
        run: |
          echo "GITHUB_COMMIT_SHORT_HASH=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      
      - name: Get Repository Name
        run: |
          echo "REPO=$(echo ${{ github.repository }} | tr [:upper:] [:lower:])"
          echo "REPO=$(${{ github.repository }} | tr [:upper:] [:lower:])" >> $GITHUB_ENV
          
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.GITHUB_COMMIT_SHORT_HASH }}
            ghcr.io/${{ env.REPO }}:latest
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}